WebPatient/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPatient.DAL;
using WebPatient.Models;

namespace WebPatient.Controllers
{
    public class PatientController : Controller
    {
        private PatientsContext context;

        public PatientController()
        {
            this.context = new PatientsContext();
        }

        [HttpGet]
        public ActionResult EditPatientModal(long PatientID)
        {
            return PartialView("_EditPatientsModal", context.Patients.Where(p => p.PatientID == PatientID).FirstOrDefault());
        }

        [HttpGet]
        public ActionResult AddPatient()
        {
            return View("AddPatient", new Patient());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPatient(Patient model)
        {
            if (ModelState.IsValid)
            {
                using (var db = this.context)
                {
                    db.Patients.Add(model);
                    db.SaveChanges();
                }

                return RedirectToActionPermanent("Index", "Home");
            }

            ModelState.AddModelError("name", "");

            return View("AddPatient", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdatePatient(Patient model)
        {
            if (ModelState.IsValid)
            {
                using (var db = this.context)
                {

                    var result = db.Patients.SingleOrDefault(p => p.PatientID == model.PatientID);
                    if (result != null)
                    {
                        db.Entry(result).CurrentValues.SetValues(model);
                        db.SaveChanges();
                    }
                }
                return Content("{\"success\": \"Пациент успешно сохранен\"}", "application/json");
            }

            ModelState.AddModelError("name", "");
            return PartialView("_GetPatientsModal", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePatient(Patient model)
        {
            try
            {
                using (var db = this.context)
                {
                    var result = db.Patients.SingleOrDefault(p => p.PatientID == model.PatientID);
                    if (result != null)
                    {
                        db.Patients.Remove(result);
                        db.SaveChanges();
                        return Content("{\"success\": \"Пациент успешно удален\"}", "application/json");
                    }
                    return Content("{\"error\": \"Пациент в базе не найден\"}", "application/json");
                }
            }
            catch (Exception ex)
            {
                return Content("{\"error\": \"Пациент не удален " + ex.Message + "\"}", "application/json");
            }

        }
    }
}

WebPatient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Пациенты</title>
    @Styles.Render("~/bundles/css")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <a href="../" class="navbar-brand">Тестовое задание</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">@Html.ActionLink("Пациенты", "Index", "Home", new { @class = "nav-link" })</li>
                <li class="nav-item active"> <a class="nav-link" href="@Url.Action("AddPatient", "Patient", new { id = UrlParameter.Optional })">Добавить пациента</a></li>
            </ul>

        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <hr />
        @RenderSection("featured", required: false)
        <footer>
            <p>&copy; @DateTime.Now.Year - Тестовое задание Комтек</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>